### ISSUE TITLE
Connection error when activating ios app with less than 24hrs in Emoncms

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms-ios#2]
https://community.openenergymonitor.org/t/app-myelectric-connection-error-on-ios/5975/4

> It seems I was too hasty, I had activated the app with less than a day’s worth of history on emoncms, but now everything is working fine. I guess the error came from trying to fetch non-existing data to get the day total.

**Comment by mattjgalloway** [comment]
This is fixed in the code now.
