### ISSUE TITLE
Cannot compile with Xcode 10

### ISSUE THREAD

**Issue by Scarzer** [emoncms/emoncms-ios#3]
After pulling this project from github and building the application, compilation errors with Former, Charts, Realm and RealmSwift are preventing building of the project. 

I'm seeing the following errors:

Realm:
![image](https://user-images.githubusercontent.com/1868926/49606941-b6930600-f962-11e8-970b-f92e607714f8.png)

EmonCMSiOS: 
![image](https://user-images.githubusercontent.com/1868926/49606987-cdd1f380-f962-11e8-8570-08c08a4bf4b1.png)

RealmSwift:
![image](https://user-images.githubusercontent.com/1868926/49607018-dde9d300-f962-11e8-8d5c-491e75f1a7d2.png)

Former: 
![image](https://user-images.githubusercontent.com/1868926/49607055-f5c15700-f962-11e8-894f-bb5bbe89c9ea.png)

RxRealm:
![image](https://user-images.githubusercontent.com/1868926/49607085-040f7300-f963-11e8-90a1-273243ac89e2.png)

**Comment by glynhudson** [comment]
Mmm any idea @mattjgalloway ?

**Comment by mattjgalloway** [comment]
@Scarzer Ah thanks for pointing this out! I will need to take a look at this.

FYI - I've not had much time of late to maintain this stuff. I personally use it every day, but haven't been actively developing it. I would like to get back to it some time. I can't commit right now to a specific time.

If you're interested in helping out then let me know! I imagine that bringing this up-to-date will be a matter of updating to latest Swift syntax, and updating the Cocoapods.

Also - do note that you can download the app from the App Store if you just want to use it.

**Comment by mattjgalloway** [comment]
@Scarzer - it should all work now.
