### ISSUE TITLE
Numerical scaling issues 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms-ios#52]
A user recently posted this strange decimal place scaling issue. Seemed to coincide with iOS 13.1.3 update 

![aJQB32-M](https://user-images.githubusercontent.com/758844/67223428-2305df00-f427-11e9-998b-684444d79d8e.jpg)

**Comment by mattjgalloway** [comment]
This was fixed in 9112118156cb57ee6e50ca6da808f8e97ada12ff.

Need to do an App Store update sometime.
