### ISSUE TITLE
App not available in UK store

### ISSUE THREAD

**Issue by mnbf9rca** [emoncms/emoncms-ios#62]
I'm in the UK. When i try to install the app, I get told "This app is not currently available in your region or country".

Is there a way to make it available in the UK?

![IMG_7729](https://user-images.githubusercontent.com/1039058/209238146-d4d2ecb9-8170-46f8-95c3-d788e18efd39.png)

**Comment by glynhudson** [comment]
This has now been fixed, apologies for the hassle.

**Comment by mnbf9rca** [comment]
Thanks!
